apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-10-30T04:07:57Z"
  labels:
    app: goRabbitPod
  name: goRabbitPod
spec:
  containers:
      image: localhost/gorabbit:0.1
      name: gorabbit_1
      ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
    - command:
        - rabbitmq-server
      image: docker.io/library/rabbitmq:3-management-alpine
      name: some-rabbit
      ports:
        - containerPort: 15672
          hostPort: 15672
          protocol: TCP
        - containerPort: 5672
          hostPort: 5672
          protocol: TCP
      startupProbe:
        tcpSocket:
        port: 5672
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 5672
        initialDelaySeconds: 15
        periodSeconds: 20
      volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbit_data
  volumes:
    - name: rabbit_data
      hostPath:
        path: ./rabbit_data
        type: DirectoryOrCreate