# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.9.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-10-30T04:07:57Z"
  labels:
    app: goRabbitPod
  name: goRabbitPod
spec:
  containers:
    - command:
        - rabbitmq-server
      env:
        - name: PATH
          value: /opt/rabbitmq/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: HOSTNAME
          value: my-rabbit
        - name: RABBITMQ_PGP_KEY_ID
          value: 0x0A9AF2115F4687BD29803A206B73A36E6026DFCA
        - name: OPENSSL_PGP_KEY_IDS
          value:
            0x8657ABB260F056B1E5190839D9C4D26D0E604491 0x5B2545DAB21995F4088CEFAA36CEE4DEB00CFE33
            0xED230BEC4D4F2518B9D7DF41F0DB4D21C1D35231 0xC1F33DD8CE1D4CC613AF14DA9195C48241FBF7DD
            0x7953AC1FBC3DC8B3B292393ED5E9E43F7DF9EE8C 0xE5E52560DD91C556DDBDA5D02064C53641C25E5D
        - name: OTP_VERSION
          value: 23.1.1
        - name: OPENSSL_VERSION
          value: 1.1.1h
        - name: HOME
          value: /var/lib/rabbitmq
        - name: RABBITMQ_DATA_DIR
          value: /var/lib/rabbitmq
        - name: LANGUAGE
          value: C.UTF-8
        - name: OPENSSL_SOURCE_SHA256
          value: 5c9ca8774bd7b03e5784f26ae9e9e6d749c9da2438545077e6b3d755a06595d9
        - name: RABBITMQ_VERSION
          value: 3.8.9
        - name: LANG
          value: C.UTF-8
        - name: RABBITMQ_LOGS
          value: "-"
        - name: RABBITMQ_HOME
          value: /opt/rabbitmq
        - name: LC_ALL
          value: C.UTF-8
        - name: container
          value: podman
        - name: OTP_SOURCE_SHA256
          value: 8094484d94bce21d76f3a6c6137098839e7bc121e170c08b472f980296684ac9
      image: docker.io/library/rabbitmq:3-management-alpine
      name: some-rabbit
      ports:
        - containerPort: 15672
          hostPort: 15672
          protocol: TCP
        - containerPort: 5672
          hostPort: 5672
          protocol: TCP
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbit-data
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
        seLinuxOptions: {}
      workingDir: /
  volumes:
    - name: rabbit-data
      hostPath:
        path: ./rabbit-data
        type: DirectoryOrCreate
status: {}
