apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-10-30T04:07:57Z"
  labels:
    app: probepod
  name: probepod
spec:
  containers:
  # Go container
    - env:
        - name: HOSTNAME
          value: probe_1
        - name: container
          value: podman
      image: sudosapan.com/probesvc:0.1
      name: probe-1
      ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: true
        privileged: false
        readOnlyRootFilesystem: false
      workingDir: /
      livenessProbe:
        httpGet:
          path: /live
          port: 8080
          httpHeaders:
          - name: SAPAN-HEADER
            value: SAPAN_VASHISHTH
        initialDelaySeconds: 5
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
          httpHeaders:
          - name: SAPAN-HEADER
            value: SAPAN_VASHISHTH
        initialDelaySeconds: 5
        periodSeconds: 5
status: {}
