apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-10-30T04:07:57Z"
  labels:
    app: goRedisPod
  name: goRedisPod
spec:
  containers:
  # Go container
    - env:
        - name: HOSTNAME
          value: goredis_1
        - name: container
          value: podman
        - name: REDIS_ADDR
          value: localhost:6379
      image: go-redis
      name: goredis-1
      ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
        seLinuxOptions: {}
      workingDir: /
  # Redis 
    - command:
      - redis-server
      env:
      - name: PATH
        value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - name: TERM
        value: xterm
      - name: container
        value: podman
      - name: REDIS_VERSION
        value: 6.0.9
      - name: REDIS_DOWNLOAD_URL
        value: http://download.redis.io/releases/redis-6.0.9.tar.gz
      - name: REDIS_DOWNLOAD_SHA
        value: dc2bdcf81c620e9f09cfd12e85d3bc631c897b2db7a55218fd8a65eaa37f86dd
      - name: HOSTNAME
      image: docker.io/library/redis:alpine
      name: redb
      ports:
      - containerPort: 6379
        hostPort: 6379
        protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          drop:
          - CAP_MKNOD
          - CAP_NET_RAW
          - CAP_AUDIT_WRITE
        privileged: false
        readOnlyRootFilesystem: false
        seLinuxOptions: {}
      workingDir: /data
status: {}
